apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
        - name: cicd-demo
          image: rituraj4164/cicd-demo:44dd7ce0c3a2d5bacf0a8cba4768faee9c40e455
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
